# Generated by Django 4.2.5 on 2023-10-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='products',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='user',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
