# Generated by Django 4.2.5 on 2023-10-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_product_brand'),
        ('shopflow', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='shopflow.CartItem', to='estore.product'),
        ),
    ]
