# Generated by Django 4.2.5 on 2023-10-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_product_brand'),
        ('shopflow', '0005_remove_favorites_products_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_favrorites', to='estore.product'),
        ),
    ]
