# Generated by Django 4.2.5 on 2023-10-14 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_product_brand'),
        ('shopflow', '0006_favorites_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_favrorites', to='estore.product'),
        ),
    ]
